version: "1"
services:
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
    app:
        build: ./
        container_name: app
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - redis
